# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[40,)" #mandatory
issueTrackerURL="https://github.com/Sinhika/cthon/issues"
license="LGPL 3"

[[mods]]
modId="cthon"
version="${file.jarVersion}"
displayName="akkamaddi's Simple Cthon"
logo="cthon_logo.png"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/cthon/1.16/update.json"
displayURL="http://minecraft.curseforge.com/projects/akkamaddis-simple-cthon"
credits="akkamaddi (original mod), Sinhika (maintenance, ports)."
authors="akkamaddi, Sinhika"
description='''Cthon, a toxic Nether ore that yields a rare, very strong metal when processed.

Additional Credits: akkamaddi, for updating the cthon ore texture.
'''

[[dependencies.cthon]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,41)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cthon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.cthon]]
    modId="simplecorelib"
    mandatory=true
    versionRange="[1.18.2-4.3.1.0,1.18.2-4.4.0.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cthon]]
    modId="fusion"
    mandatory=true
    versionRange="[1.18.1-4.1.1.1,1.18.2-4.2.0.0)"
    ordering="NONE"
    side="BOTH"

#[[dependencies.cthon]]
#        modId="silents_mechanisms"
#        mandatory=false
#        versionRange="[0.8.9,)"
#        ordering="BEFORE"
#        side="BOTH"
#        
#[[dependencies.cthon]]
#        modId="silentgear"
#        mandatory=false
#        versionRange="[1.16.3-2.6.5,)"
#        ordering="BEFORE"
#        side="BOTH"
#        
