# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="${loader_version_range}" #mandatory
issueTrackerURL="https://github.com/Sinhika/cthon/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
logo="cthon_logo.png"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/cthon/1.20/update.json"
displayURL="http://minecraft.curseforge.com/projects/akkamaddis-simple-cthon"
credits="akkamaddi (original mod), Sinhika (maintenance, ports)."
authors="akkamaddi, Sinhika"
description='''Cthon, a toxic Nether ore that yields a rare, very strong metal when processed.

Additional Credits: akkamaddi, for updating the cthon ore texture.
'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.${mod_id}]]
    modId="simplecorelib"
    mandatory=true
    versionRange="${simplecore_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="fusion"
    mandatory=true
    versionRange="${fusion_range}"
    ordering="NONE"
    side="BOTH"

